# Generated by Django 4.2.3 on 2023-07-25 15:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('learning_logs', '0007_model_rename_topic_section_delete_entry_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='model',
            options={'verbose_name_plural': 'models'},
        ),
        migrations.AlterField(
            model_name='model',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to='images/'),
        ),
    ]
