# Generated by Django 4.2.3 on 2023-07-25 16:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('learning_logs', '0009_alter_model_image'),
    ]

    operations = [
        migrations.AlterField(
            model_name='model',
            name='image',
            field=models.ImageField(blank=True, upload_to='images/'),
        ),
        migrations.AlterField(
            model_name='model',
            name='name',
            field=models.CharField(blank=True, max_length=50),
        ),
        migrations.AlterField(
            model_name='model',
            name='text',
            field=models.TextField(blank=True, max_length=5000),
        ),
        migrations.AlterField(
            model_name='section',
            name='text',
            field=models.CharField(blank=True, max_length=200),
        ),
    ]
