# Generated by Django 4.2.3 on 2023-07-25 16:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('learning_logs', '0010_alter_model_image_alter_model_name_alter_model_text_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='model',
            name='image',
            field=models.ImageField(blank=True, default=None, null=True, upload_to='images/'),
        ),
        migrations.AlterField(
            model_name='model',
            name='name',
            field=models.CharField(blank=True, default=None, max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='model',
            name='text',
            field=models.TextField(blank=True, default=None, max_length=5000, null=True),
        ),
        migrations.AlterField(
            model_name='section',
            name='text',
            field=models.CharField(max_length=200),
        ),
    ]
