# Generated by Django 4.2.3 on 2023-07-25 16:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('learning_logs', '0011_alter_model_image_alter_model_name_alter_model_text_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='model',
            name='image',
            field=models.ImageField(null=True, upload_to='images/'),
        ),
        migrations.AlterField(
            model_name='model',
            name='name',
            field=models.CharField(max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='model',
            name='text',
            field=models.TextField(max_length=5000, null=True),
        ),
    ]
